/**
 * this function will create a link to search a term on a number of websites with google
 * https://www.google.com/search?q=button+site%3Amaterial-ui.com+OR+site%3Aant.design+OR+site%3Aschema.org
 * @param {array of strings} sites the sites the search is limited to
 * @param {string} searchTerm the term that is being searched
 * @returns {string} a link for a search query
 */
function googleFindInSites(sites, searchTerm) {
	let googleBase = "https://www.google.com/search?q=";
	let siteStart = "site%3A";
	let siteOR = "OR";
	let separator = "+";
	let rvArr = [googleBase, searchTerm];
	let sitesMapped = sites.map(site => {
		return `${siteStart}${site}`;
	});
	rvArr.push(sitesMapped.reduce((prev, cur, curIdx) => {
		if (curIdx == 0) return prev + separator + cur;
		return prev + separator + siteOR + separator + cur;
	}));
	return rvArr.reduce((prev, cur, curIdx) => {
		if (curIdx == 1) return prev + cur;
		return prev + separator + cur;
	});
}

function googleFindManyTermsInSites(sites, searchTerms) {
	return searchTerms.map((val) => googleFindInSites(sites, val)).reduce((prev, cur) => prev + "\n" + cur
		, "");
};

let term = "button";
let limitToSites = ["material-ui.com", "ant.design", "schema.org"]

let terms = [
	"Element"
	, "DataType"
	, "DataTypeProperty"
	, "UIElement"
	, "Action"
	, "State"
	, "SemanticFlag"
	, "SemanticProperty"
	, "PropertyValueSpecification"
	, "multipleValues"
	, "valueName"
	, "defaultValue"
	, "valueRequired"
	, "readonlyValue"
	, "BooleanType"
	, "isActive"
	, "isInactive"
	, "isOn"
	, "isOff"
	, "isChecked"
	, "isUnchecked"
	, "isDisabled"
	, "isEnabled"
	, "NumericTypeProperty"
	, "min"
	, "max"
	, "currentValue"
	, "stepValue"
	, "TextTypeProperty"
	, "valuePattern"
	, "valueMinLength"
	, "valueMaxLength"
	, "MediaDataType"
	, "image"
	, "audio"
	, "video"
	, "MediaDataTypeProperty"
	, "isPlaying"
	, "VisualExpression"
	, "color"
	, "font"
	, "italic"
	, "bold"
	, "underlined"
	, "background"
	, "highlight"
	, "Some"
	, "selectedIndex"
	, "activeTabIndex"
	, "selectedSet"
	, "unselectedSet"
	, "UserActionState"
	, "HoverState"
	, "FocusState"
	, "PressedState"
	, "DraggingState"
	, "UserAction"
	, "DetailAction"
	, "NavigateAction"
	, "BrowseAction"
	, "FavoriteAction"
	, "SaveAction"
	, "DragAction"
	, "DropAction"
	, "ResizeAction"
	, "ScrollAction"
	, "DismissAction"
	, "ConfirmAction"
	, "DeleteAction"
	, "ZoomAction"
	, "AlignAction"
	, "BackAction"
	, "DeviceSpecificAction"
	, "ClickAction"
	, "TouchDownAction"
	, "KeyDownAction"
	, "ChangeOrientationAction"
	, "SwipeAction"
	, "PointAction"
	, "MediaAction"
	, "UploadAction"
	, "DownloadAction"
	, "RecordAction"
	, "StartAction"
	, "StopAction"
	, "PauseAction"
	, "MediaPartAction"
	, "MarkAction"
	, "AnnotateAction"
	, "UIElementState"
	, "FixedState"
	, "LooseState"
	, "MinifiedState"
	, "ExpandedState"
	, "MaximizedState"
	, "MinimizedState"
	, "FloatingState"
	, "OpenState"
	, "ClosedState"
	, "SortedState"
	, "UnsortedState"
	, "FilteredState"
	, "UnfilteredState"
	, "UIStack"
	, "BlankState"
	, "LoadingState"
	, "PartialState"
	, "ErrorState"
	, "IdealState"
	, "UIElementTransitionState"
	, "ClosingState"
	, "OpeningState"
	, "SkeletonState"
	, "IssueSeverity"
	, "priority"
	, "importance"
	, "IssueSeverityType"
	, "Default"
	, "Alert"
	, "Warning"
	, "Error"
	, "Incomplete"
	, "Empty"
	, "AtomUIElement"
	, "Icon"
	, "Label"
	, "Title"
	, "Subtitle"
	, "Input"
	, "Button"
	, "Heading"
	, "Subheading"
	, "Checkbox"
	, "Radiobutton"
	, "Datepicker"
	, "Timepicker"
	, "Switch"
	, "Textfield"
	, "Link"
	, "Avatar"
	, "Shape"
	, "Circle"
	, "Triangle"
	, "Rectangle"
	, "Ellipsis"
	, "Star"
	, "MoleculeUIElement"
	, "NavigationBar"
	, "Tooltip"
	, "Searchbar"
	, "Searchfield"
	, "Thumbnail"
	, "Dialog"
	, "Step"
	, "Divider"
	, "Dropdown"
	, "Pagination"
	, "OrganismUIElement"
	, "Header"
	, "Footer"
	, "Section"
	, "Card"
	, "ContainerUIElement"
	, "DirectoryStructure"
	, "TreeView"
	, "Tabs"
	, "List"
	, "Container"
	, "Table"
	, "Grid"
	, "SingleSelection"
	, "MultiSelection"
	, "ColumnHeader"
	, "StructuralUIElement"
	, "ABTest"
	, "Form"
	, "Template"
	, "Page"
	, "Placeholder"
	, "Context"
	, "Scope"
	, "Constraint"
	, "Autocomplete"
	, "variation"
	, "aVersion"
	, "bVersion"
	, "triggers"
	, "slot"
	, "unorderedSlots"
	, "orderedSlots"
	, "a11y"
	, "ariaLabel"
	, "moreInfo"
	, "valueText"
	, "CommunicateAction"
	, "CommentAction"
	, "ReplyAction"
	, "ReactAction"
	, "HierarchyFlag"
	, "isProminent"
	, "isRaised"
	, "isDense"
	, "isMini"
	, "isPrimary"
	, "isSecondary"
	, "isTertiary"
	, "isCurrent"
	, "isOverlay"
	, "isHidden"
	, "isModal"
	, "DescriptionFlag"
	, "isHelp"
	, "isContent"
	, "isProgress"
	, "OutcomeProperty"
	, "result"
	, "output"
	, "status"
	, "NavigationProperty"
	, "menu"
	, "settings"
	, "ContextProperty"
	, "role"
	, "user"
	, "group"
];
googleFindInSites(limitToSites, term);
console.log(googleFindManyTermsInSites(limitToSites, terms));